/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateEmployeeDto,
  EmployeeListResponseDto,
  EmployeeResponseDto,
  EmployeesControllerFindAllParams,
  UpdateEmployeeDto
} from '../../model';

import { httpRequest } from '../../http-client';




/**
 * @summary 従業員作成
 */
export const employeesControllerCreate = (
    createEmployeeDto: CreateEmployeeDto,
 signal?: AbortSignal
) => {


      return httpRequest<EmployeeResponseDto>(
      {url: `/api/v1/employees`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createEmployeeDto, signal
    },
      );
    }



export const getEmployeesControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof employeesControllerCreate>>, TError,{data: CreateEmployeeDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof employeesControllerCreate>>, TError,{data: CreateEmployeeDto}, TContext> => {

const mutationKey = ['employeesControllerCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof employeesControllerCreate>>, {data: CreateEmployeeDto}> = (props) => {
          const {data} = props ?? {};

          return  employeesControllerCreate(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EmployeesControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof employeesControllerCreate>>>
    export type EmployeesControllerCreateMutationBody = CreateEmployeeDto
    export type EmployeesControllerCreateMutationError = unknown

    /**
 * @summary 従業員作成
 */
export const useEmployeesControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof employeesControllerCreate>>, TError,{data: CreateEmployeeDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof employeesControllerCreate>>,
        TError,
        {data: CreateEmployeeDto},
        TContext
      > => {
      return useMutation(getEmployeesControllerCreateMutationOptions(options), queryClient);
    }
    /**
 * @summary 従業員一覧
 */
export const employeesControllerFindAll = (
    params?: EmployeesControllerFindAllParams,
 signal?: AbortSignal
) => {


      return httpRequest<EmployeeListResponseDto>(
      {url: `/api/v1/employees`, method: 'GET',
        params, signal
    },
      );
    }




export const getEmployeesControllerFindAllQueryKey = (params?: EmployeesControllerFindAllParams,) => {
    return [
    `/api/v1/employees`, ...(params ? [params] : [])
    ] as const;
    }


export const getEmployeesControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof employeesControllerFindAll>>, TError = unknown>(params?: EmployeesControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof employeesControllerFindAll>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEmployeesControllerFindAllQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof employeesControllerFindAll>>> = ({ signal }) => employeesControllerFindAll(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof employeesControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EmployeesControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof employeesControllerFindAll>>>
export type EmployeesControllerFindAllQueryError = unknown


export function useEmployeesControllerFindAll<TData = Awaited<ReturnType<typeof employeesControllerFindAll>>, TError = unknown>(
 params: undefined |  EmployeesControllerFindAllParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof employeesControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof employeesControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof employeesControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEmployeesControllerFindAll<TData = Awaited<ReturnType<typeof employeesControllerFindAll>>, TError = unknown>(
 params?: EmployeesControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof employeesControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof employeesControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof employeesControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEmployeesControllerFindAll<TData = Awaited<ReturnType<typeof employeesControllerFindAll>>, TError = unknown>(
 params?: EmployeesControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof employeesControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 従業員一覧
 */

export function useEmployeesControllerFindAll<TData = Awaited<ReturnType<typeof employeesControllerFindAll>>, TError = unknown>(
 params?: EmployeesControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof employeesControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEmployeesControllerFindAllQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary 従業員詳細
 */
export const employeesControllerFindOne = (
    id: string,
 signal?: AbortSignal
) => {


      return httpRequest<EmployeeResponseDto>(
      {url: `/api/v1/employees/${id}`, method: 'GET', signal
    },
      );
    }




export const getEmployeesControllerFindOneQueryKey = (id: string,) => {
    return [
    `/api/v1/employees/${id}`
    ] as const;
    }


export const getEmployeesControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof employeesControllerFindOne>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof employeesControllerFindOne>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEmployeesControllerFindOneQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof employeesControllerFindOne>>> = ({ signal }) => employeesControllerFindOne(id, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof employeesControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EmployeesControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof employeesControllerFindOne>>>
export type EmployeesControllerFindOneQueryError = unknown


export function useEmployeesControllerFindOne<TData = Awaited<ReturnType<typeof employeesControllerFindOne>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof employeesControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof employeesControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof employeesControllerFindOne>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEmployeesControllerFindOne<TData = Awaited<ReturnType<typeof employeesControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof employeesControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof employeesControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof employeesControllerFindOne>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEmployeesControllerFindOne<TData = Awaited<ReturnType<typeof employeesControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof employeesControllerFindOne>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 従業員詳細
 */

export function useEmployeesControllerFindOne<TData = Awaited<ReturnType<typeof employeesControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof employeesControllerFindOne>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEmployeesControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary 従業員更新
 */
export const employeesControllerUpdate = (
    id: string,
    updateEmployeeDto: UpdateEmployeeDto,
 signal?: AbortSignal
) => {


      return httpRequest<EmployeeResponseDto>(
      {url: `/api/v1/employees/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateEmployeeDto, signal
    },
      );
    }



export const getEmployeesControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof employeesControllerUpdate>>, TError,{id: string;data: UpdateEmployeeDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof employeesControllerUpdate>>, TError,{id: string;data: UpdateEmployeeDto}, TContext> => {

const mutationKey = ['employeesControllerUpdate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof employeesControllerUpdate>>, {id: string;data: UpdateEmployeeDto}> = (props) => {
          const {id,data} = props ?? {};

          return  employeesControllerUpdate(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EmployeesControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof employeesControllerUpdate>>>
    export type EmployeesControllerUpdateMutationBody = UpdateEmployeeDto
    export type EmployeesControllerUpdateMutationError = unknown

    /**
 * @summary 従業員更新
 */
export const useEmployeesControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof employeesControllerUpdate>>, TError,{id: string;data: UpdateEmployeeDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof employeesControllerUpdate>>,
        TError,
        {id: string;data: UpdateEmployeeDto},
        TContext
      > => {
      return useMutation(getEmployeesControllerUpdateMutationOptions(options), queryClient);
    }
