/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateDepartmentDto,
  CreateWorkPatternDto,
  DepartmentResponseDto,
  WorkPatternResponseDto
} from '../../model';

import { httpRequest } from '../../http-client';




/**
 * @summary 部署作成
 */
export const settingsControllerCreateDepartment = (
    createDepartmentDto: CreateDepartmentDto,
 signal?: AbortSignal
) => {


      return httpRequest<DepartmentResponseDto>(
      {url: `/api/v1/admin/departments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createDepartmentDto, signal
    },
      );
    }



export const getSettingsControllerCreateDepartmentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settingsControllerCreateDepartment>>, TError,{data: CreateDepartmentDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof settingsControllerCreateDepartment>>, TError,{data: CreateDepartmentDto}, TContext> => {

const mutationKey = ['settingsControllerCreateDepartment'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof settingsControllerCreateDepartment>>, {data: CreateDepartmentDto}> = (props) => {
          const {data} = props ?? {};

          return  settingsControllerCreateDepartment(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SettingsControllerCreateDepartmentMutationResult = NonNullable<Awaited<ReturnType<typeof settingsControllerCreateDepartment>>>
    export type SettingsControllerCreateDepartmentMutationBody = CreateDepartmentDto
    export type SettingsControllerCreateDepartmentMutationError = unknown

    /**
 * @summary 部署作成
 */
export const useSettingsControllerCreateDepartment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settingsControllerCreateDepartment>>, TError,{data: CreateDepartmentDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof settingsControllerCreateDepartment>>,
        TError,
        {data: CreateDepartmentDto},
        TContext
      > => {
      return useMutation(getSettingsControllerCreateDepartmentMutationOptions(options), queryClient);
    }
    /**
 * @summary 部署一覧
 */
export const settingsControllerFindDepartments = (

 signal?: AbortSignal
) => {


      return httpRequest<DepartmentResponseDto[]>(
      {url: `/api/v1/admin/departments`, method: 'GET', signal
    },
      );
    }




export const getSettingsControllerFindDepartmentsQueryKey = () => {
    return [
    `/api/v1/admin/departments`
    ] as const;
    }


export const getSettingsControllerFindDepartmentsQueryOptions = <TData = Awaited<ReturnType<typeof settingsControllerFindDepartments>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsControllerFindDepartments>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSettingsControllerFindDepartmentsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof settingsControllerFindDepartments>>> = ({ signal }) => settingsControllerFindDepartments(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof settingsControllerFindDepartments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SettingsControllerFindDepartmentsQueryResult = NonNullable<Awaited<ReturnType<typeof settingsControllerFindDepartments>>>
export type SettingsControllerFindDepartmentsQueryError = unknown


export function useSettingsControllerFindDepartments<TData = Awaited<ReturnType<typeof settingsControllerFindDepartments>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsControllerFindDepartments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof settingsControllerFindDepartments>>,
          TError,
          Awaited<ReturnType<typeof settingsControllerFindDepartments>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSettingsControllerFindDepartments<TData = Awaited<ReturnType<typeof settingsControllerFindDepartments>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsControllerFindDepartments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof settingsControllerFindDepartments>>,
          TError,
          Awaited<ReturnType<typeof settingsControllerFindDepartments>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSettingsControllerFindDepartments<TData = Awaited<ReturnType<typeof settingsControllerFindDepartments>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsControllerFindDepartments>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 部署一覧
 */

export function useSettingsControllerFindDepartments<TData = Awaited<ReturnType<typeof settingsControllerFindDepartments>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsControllerFindDepartments>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSettingsControllerFindDepartmentsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary 部署更新
 */
export const settingsControllerUpdateDepartment = (
    id: string,
    createDepartmentDto: CreateDepartmentDto,
 signal?: AbortSignal
) => {


      return httpRequest<DepartmentResponseDto>(
      {url: `/api/v1/admin/departments/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: createDepartmentDto, signal
    },
      );
    }



export const getSettingsControllerUpdateDepartmentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settingsControllerUpdateDepartment>>, TError,{id: string;data: CreateDepartmentDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof settingsControllerUpdateDepartment>>, TError,{id: string;data: CreateDepartmentDto}, TContext> => {

const mutationKey = ['settingsControllerUpdateDepartment'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof settingsControllerUpdateDepartment>>, {id: string;data: CreateDepartmentDto}> = (props) => {
          const {id,data} = props ?? {};

          return  settingsControllerUpdateDepartment(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SettingsControllerUpdateDepartmentMutationResult = NonNullable<Awaited<ReturnType<typeof settingsControllerUpdateDepartment>>>
    export type SettingsControllerUpdateDepartmentMutationBody = CreateDepartmentDto
    export type SettingsControllerUpdateDepartmentMutationError = unknown

    /**
 * @summary 部署更新
 */
export const useSettingsControllerUpdateDepartment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settingsControllerUpdateDepartment>>, TError,{id: string;data: CreateDepartmentDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof settingsControllerUpdateDepartment>>,
        TError,
        {id: string;data: CreateDepartmentDto},
        TContext
      > => {
      return useMutation(getSettingsControllerUpdateDepartmentMutationOptions(options), queryClient);
    }
    /**
 * @summary 勤務形態作成
 */
export const settingsControllerCreateWorkPattern = (
    createWorkPatternDto: CreateWorkPatternDto,
 signal?: AbortSignal
) => {


      return httpRequest<WorkPatternResponseDto>(
      {url: `/api/v1/admin/work-patterns`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createWorkPatternDto, signal
    },
      );
    }



export const getSettingsControllerCreateWorkPatternMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settingsControllerCreateWorkPattern>>, TError,{data: CreateWorkPatternDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof settingsControllerCreateWorkPattern>>, TError,{data: CreateWorkPatternDto}, TContext> => {

const mutationKey = ['settingsControllerCreateWorkPattern'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof settingsControllerCreateWorkPattern>>, {data: CreateWorkPatternDto}> = (props) => {
          const {data} = props ?? {};

          return  settingsControllerCreateWorkPattern(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SettingsControllerCreateWorkPatternMutationResult = NonNullable<Awaited<ReturnType<typeof settingsControllerCreateWorkPattern>>>
    export type SettingsControllerCreateWorkPatternMutationBody = CreateWorkPatternDto
    export type SettingsControllerCreateWorkPatternMutationError = unknown

    /**
 * @summary 勤務形態作成
 */
export const useSettingsControllerCreateWorkPattern = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settingsControllerCreateWorkPattern>>, TError,{data: CreateWorkPatternDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof settingsControllerCreateWorkPattern>>,
        TError,
        {data: CreateWorkPatternDto},
        TContext
      > => {
      return useMutation(getSettingsControllerCreateWorkPatternMutationOptions(options), queryClient);
    }
    /**
 * @summary 勤務形態一覧
 */
export const settingsControllerFindWorkPatterns = (

 signal?: AbortSignal
) => {


      return httpRequest<WorkPatternResponseDto[]>(
      {url: `/api/v1/admin/work-patterns`, method: 'GET', signal
    },
      );
    }




export const getSettingsControllerFindWorkPatternsQueryKey = () => {
    return [
    `/api/v1/admin/work-patterns`
    ] as const;
    }


export const getSettingsControllerFindWorkPatternsQueryOptions = <TData = Awaited<ReturnType<typeof settingsControllerFindWorkPatterns>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsControllerFindWorkPatterns>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSettingsControllerFindWorkPatternsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof settingsControllerFindWorkPatterns>>> = ({ signal }) => settingsControllerFindWorkPatterns(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof settingsControllerFindWorkPatterns>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SettingsControllerFindWorkPatternsQueryResult = NonNullable<Awaited<ReturnType<typeof settingsControllerFindWorkPatterns>>>
export type SettingsControllerFindWorkPatternsQueryError = unknown


export function useSettingsControllerFindWorkPatterns<TData = Awaited<ReturnType<typeof settingsControllerFindWorkPatterns>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsControllerFindWorkPatterns>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof settingsControllerFindWorkPatterns>>,
          TError,
          Awaited<ReturnType<typeof settingsControllerFindWorkPatterns>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSettingsControllerFindWorkPatterns<TData = Awaited<ReturnType<typeof settingsControllerFindWorkPatterns>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsControllerFindWorkPatterns>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof settingsControllerFindWorkPatterns>>,
          TError,
          Awaited<ReturnType<typeof settingsControllerFindWorkPatterns>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSettingsControllerFindWorkPatterns<TData = Awaited<ReturnType<typeof settingsControllerFindWorkPatterns>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsControllerFindWorkPatterns>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 勤務形態一覧
 */

export function useSettingsControllerFindWorkPatterns<TData = Awaited<ReturnType<typeof settingsControllerFindWorkPatterns>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsControllerFindWorkPatterns>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSettingsControllerFindWorkPatternsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary 勤務形態更新
 */
export const settingsControllerUpdateWorkPattern = (
    id: string,
    createWorkPatternDto: CreateWorkPatternDto,
 signal?: AbortSignal
) => {


      return httpRequest<WorkPatternResponseDto>(
      {url: `/api/v1/admin/work-patterns/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: createWorkPatternDto, signal
    },
      );
    }



export const getSettingsControllerUpdateWorkPatternMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settingsControllerUpdateWorkPattern>>, TError,{id: string;data: CreateWorkPatternDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof settingsControllerUpdateWorkPattern>>, TError,{id: string;data: CreateWorkPatternDto}, TContext> => {

const mutationKey = ['settingsControllerUpdateWorkPattern'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof settingsControllerUpdateWorkPattern>>, {id: string;data: CreateWorkPatternDto}> = (props) => {
          const {id,data} = props ?? {};

          return  settingsControllerUpdateWorkPattern(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SettingsControllerUpdateWorkPatternMutationResult = NonNullable<Awaited<ReturnType<typeof settingsControllerUpdateWorkPattern>>>
    export type SettingsControllerUpdateWorkPatternMutationBody = CreateWorkPatternDto
    export type SettingsControllerUpdateWorkPatternMutationError = unknown

    /**
 * @summary 勤務形態更新
 */
export const useSettingsControllerUpdateWorkPattern = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settingsControllerUpdateWorkPattern>>, TError,{id: string;data: CreateWorkPatternDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof settingsControllerUpdateWorkPattern>>,
        TError,
        {id: string;data: CreateWorkPatternDto},
        TContext
      > => {
      return useMutation(getSettingsControllerUpdateWorkPatternMutationOptions(options), queryClient);
    }
