/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuditLogListResponseDto,
  AuditLogsControllerFindAllSystemParams,
  AuditLogsControllerFindAllTenantParams
} from '../../model';

import { httpRequest } from '../../http-client';




/**
 * @summary 全体監査ログ一覧（system_admin）
 */
export const auditLogsControllerFindAllSystem = (
    params?: AuditLogsControllerFindAllSystemParams,
 signal?: AbortSignal
) => {


      return httpRequest<AuditLogListResponseDto>(
      {url: `/api/v1/system/audit-logs`, method: 'GET',
        params, signal
    },
      );
    }




export const getAuditLogsControllerFindAllSystemQueryKey = (params?: AuditLogsControllerFindAllSystemParams,) => {
    return [
    `/api/v1/system/audit-logs`, ...(params ? [params] : [])
    ] as const;
    }


export const getAuditLogsControllerFindAllSystemQueryOptions = <TData = Awaited<ReturnType<typeof auditLogsControllerFindAllSystem>>, TError = unknown>(params?: AuditLogsControllerFindAllSystemParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditLogsControllerFindAllSystem>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuditLogsControllerFindAllSystemQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof auditLogsControllerFindAllSystem>>> = ({ signal }) => auditLogsControllerFindAllSystem(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof auditLogsControllerFindAllSystem>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuditLogsControllerFindAllSystemQueryResult = NonNullable<Awaited<ReturnType<typeof auditLogsControllerFindAllSystem>>>
export type AuditLogsControllerFindAllSystemQueryError = unknown


export function useAuditLogsControllerFindAllSystem<TData = Awaited<ReturnType<typeof auditLogsControllerFindAllSystem>>, TError = unknown>(
 params: undefined |  AuditLogsControllerFindAllSystemParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditLogsControllerFindAllSystem>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof auditLogsControllerFindAllSystem>>,
          TError,
          Awaited<ReturnType<typeof auditLogsControllerFindAllSystem>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuditLogsControllerFindAllSystem<TData = Awaited<ReturnType<typeof auditLogsControllerFindAllSystem>>, TError = unknown>(
 params?: AuditLogsControllerFindAllSystemParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditLogsControllerFindAllSystem>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof auditLogsControllerFindAllSystem>>,
          TError,
          Awaited<ReturnType<typeof auditLogsControllerFindAllSystem>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuditLogsControllerFindAllSystem<TData = Awaited<ReturnType<typeof auditLogsControllerFindAllSystem>>, TError = unknown>(
 params?: AuditLogsControllerFindAllSystemParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditLogsControllerFindAllSystem>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 全体監査ログ一覧（system_admin）
 */

export function useAuditLogsControllerFindAllSystem<TData = Awaited<ReturnType<typeof auditLogsControllerFindAllSystem>>, TError = unknown>(
 params?: AuditLogsControllerFindAllSystemParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditLogsControllerFindAllSystem>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuditLogsControllerFindAllSystemQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary テナント内監査ログ一覧（tenant_admin）
 */
export const auditLogsControllerFindAllTenant = (
    params?: AuditLogsControllerFindAllTenantParams,
 signal?: AbortSignal
) => {


      return httpRequest<AuditLogListResponseDto>(
      {url: `/api/v1/admin/audit-logs`, method: 'GET',
        params, signal
    },
      );
    }




export const getAuditLogsControllerFindAllTenantQueryKey = (params?: AuditLogsControllerFindAllTenantParams,) => {
    return [
    `/api/v1/admin/audit-logs`, ...(params ? [params] : [])
    ] as const;
    }


export const getAuditLogsControllerFindAllTenantQueryOptions = <TData = Awaited<ReturnType<typeof auditLogsControllerFindAllTenant>>, TError = unknown>(params?: AuditLogsControllerFindAllTenantParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditLogsControllerFindAllTenant>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuditLogsControllerFindAllTenantQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof auditLogsControllerFindAllTenant>>> = ({ signal }) => auditLogsControllerFindAllTenant(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof auditLogsControllerFindAllTenant>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuditLogsControllerFindAllTenantQueryResult = NonNullable<Awaited<ReturnType<typeof auditLogsControllerFindAllTenant>>>
export type AuditLogsControllerFindAllTenantQueryError = unknown


export function useAuditLogsControllerFindAllTenant<TData = Awaited<ReturnType<typeof auditLogsControllerFindAllTenant>>, TError = unknown>(
 params: undefined |  AuditLogsControllerFindAllTenantParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditLogsControllerFindAllTenant>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof auditLogsControllerFindAllTenant>>,
          TError,
          Awaited<ReturnType<typeof auditLogsControllerFindAllTenant>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuditLogsControllerFindAllTenant<TData = Awaited<ReturnType<typeof auditLogsControllerFindAllTenant>>, TError = unknown>(
 params?: AuditLogsControllerFindAllTenantParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditLogsControllerFindAllTenant>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof auditLogsControllerFindAllTenant>>,
          TError,
          Awaited<ReturnType<typeof auditLogsControllerFindAllTenant>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuditLogsControllerFindAllTenant<TData = Awaited<ReturnType<typeof auditLogsControllerFindAllTenant>>, TError = unknown>(
 params?: AuditLogsControllerFindAllTenantParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditLogsControllerFindAllTenant>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary テナント内監査ログ一覧（tenant_admin）
 */

export function useAuditLogsControllerFindAllTenant<TData = Awaited<ReturnType<typeof auditLogsControllerFindAllTenant>>, TError = unknown>(
 params?: AuditLogsControllerFindAllTenantParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditLogsControllerFindAllTenant>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuditLogsControllerFindAllTenantQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




