/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ActionMessageResponseDto,
  CreateLeaveRequestDto,
  LeaveRequestAdminListResponseDto,
  LeaveRequestListResponseDto,
  LeaveRequestResponseDto,
  LeaveRequestsControllerFindAllAdminParams,
  LeaveRequestsControllerFindMineParams
} from '../../model';

import { httpRequest } from '../../http-client';




/**
 * @summary 休暇申請作成
 */
export const leaveRequestsControllerCreate = (
    createLeaveRequestDto: CreateLeaveRequestDto,
 signal?: AbortSignal
) => {


      return httpRequest<LeaveRequestResponseDto>(
      {url: `/api/v1/leave-requests`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createLeaveRequestDto, signal
    },
      );
    }



export const getLeaveRequestsControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof leaveRequestsControllerCreate>>, TError,{data: CreateLeaveRequestDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof leaveRequestsControllerCreate>>, TError,{data: CreateLeaveRequestDto}, TContext> => {

const mutationKey = ['leaveRequestsControllerCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof leaveRequestsControllerCreate>>, {data: CreateLeaveRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  leaveRequestsControllerCreate(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LeaveRequestsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof leaveRequestsControllerCreate>>>
    export type LeaveRequestsControllerCreateMutationBody = CreateLeaveRequestDto
    export type LeaveRequestsControllerCreateMutationError = unknown

    /**
 * @summary 休暇申請作成
 */
export const useLeaveRequestsControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof leaveRequestsControllerCreate>>, TError,{data: CreateLeaveRequestDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof leaveRequestsControllerCreate>>,
        TError,
        {data: CreateLeaveRequestDto},
        TContext
      > => {
      return useMutation(getLeaveRequestsControllerCreateMutationOptions(options), queryClient);
    }
    /**
 * @summary 自身の休暇申請一覧
 */
export const leaveRequestsControllerFindMine = (
    params?: LeaveRequestsControllerFindMineParams,
 signal?: AbortSignal
) => {


      return httpRequest<LeaveRequestListResponseDto>(
      {url: `/api/v1/leave-requests`, method: 'GET',
        params, signal
    },
      );
    }




export const getLeaveRequestsControllerFindMineQueryKey = (params?: LeaveRequestsControllerFindMineParams,) => {
    return [
    `/api/v1/leave-requests`, ...(params ? [params] : [])
    ] as const;
    }


export const getLeaveRequestsControllerFindMineQueryOptions = <TData = Awaited<ReturnType<typeof leaveRequestsControllerFindMine>>, TError = unknown>(params?: LeaveRequestsControllerFindMineParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof leaveRequestsControllerFindMine>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLeaveRequestsControllerFindMineQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof leaveRequestsControllerFindMine>>> = ({ signal }) => leaveRequestsControllerFindMine(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof leaveRequestsControllerFindMine>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LeaveRequestsControllerFindMineQueryResult = NonNullable<Awaited<ReturnType<typeof leaveRequestsControllerFindMine>>>
export type LeaveRequestsControllerFindMineQueryError = unknown


export function useLeaveRequestsControllerFindMine<TData = Awaited<ReturnType<typeof leaveRequestsControllerFindMine>>, TError = unknown>(
 params: undefined |  LeaveRequestsControllerFindMineParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof leaveRequestsControllerFindMine>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof leaveRequestsControllerFindMine>>,
          TError,
          Awaited<ReturnType<typeof leaveRequestsControllerFindMine>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLeaveRequestsControllerFindMine<TData = Awaited<ReturnType<typeof leaveRequestsControllerFindMine>>, TError = unknown>(
 params?: LeaveRequestsControllerFindMineParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof leaveRequestsControllerFindMine>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof leaveRequestsControllerFindMine>>,
          TError,
          Awaited<ReturnType<typeof leaveRequestsControllerFindMine>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLeaveRequestsControllerFindMine<TData = Awaited<ReturnType<typeof leaveRequestsControllerFindMine>>, TError = unknown>(
 params?: LeaveRequestsControllerFindMineParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof leaveRequestsControllerFindMine>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 自身の休暇申請一覧
 */

export function useLeaveRequestsControllerFindMine<TData = Awaited<ReturnType<typeof leaveRequestsControllerFindMine>>, TError = unknown>(
 params?: LeaveRequestsControllerFindMineParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof leaveRequestsControllerFindMine>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLeaveRequestsControllerFindMineQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary テナント内申請一覧（tenant_admin）
 */
export const leaveRequestsControllerFindAllAdmin = (
    params?: LeaveRequestsControllerFindAllAdminParams,
 signal?: AbortSignal
) => {


      return httpRequest<LeaveRequestAdminListResponseDto>(
      {url: `/api/v1/admin/leave-requests`, method: 'GET',
        params, signal
    },
      );
    }




export const getLeaveRequestsControllerFindAllAdminQueryKey = (params?: LeaveRequestsControllerFindAllAdminParams,) => {
    return [
    `/api/v1/admin/leave-requests`, ...(params ? [params] : [])
    ] as const;
    }


export const getLeaveRequestsControllerFindAllAdminQueryOptions = <TData = Awaited<ReturnType<typeof leaveRequestsControllerFindAllAdmin>>, TError = unknown>(params?: LeaveRequestsControllerFindAllAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof leaveRequestsControllerFindAllAdmin>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLeaveRequestsControllerFindAllAdminQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof leaveRequestsControllerFindAllAdmin>>> = ({ signal }) => leaveRequestsControllerFindAllAdmin(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof leaveRequestsControllerFindAllAdmin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LeaveRequestsControllerFindAllAdminQueryResult = NonNullable<Awaited<ReturnType<typeof leaveRequestsControllerFindAllAdmin>>>
export type LeaveRequestsControllerFindAllAdminQueryError = unknown


export function useLeaveRequestsControllerFindAllAdmin<TData = Awaited<ReturnType<typeof leaveRequestsControllerFindAllAdmin>>, TError = unknown>(
 params: undefined |  LeaveRequestsControllerFindAllAdminParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof leaveRequestsControllerFindAllAdmin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof leaveRequestsControllerFindAllAdmin>>,
          TError,
          Awaited<ReturnType<typeof leaveRequestsControllerFindAllAdmin>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLeaveRequestsControllerFindAllAdmin<TData = Awaited<ReturnType<typeof leaveRequestsControllerFindAllAdmin>>, TError = unknown>(
 params?: LeaveRequestsControllerFindAllAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof leaveRequestsControllerFindAllAdmin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof leaveRequestsControllerFindAllAdmin>>,
          TError,
          Awaited<ReturnType<typeof leaveRequestsControllerFindAllAdmin>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLeaveRequestsControllerFindAllAdmin<TData = Awaited<ReturnType<typeof leaveRequestsControllerFindAllAdmin>>, TError = unknown>(
 params?: LeaveRequestsControllerFindAllAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof leaveRequestsControllerFindAllAdmin>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary テナント内申請一覧（tenant_admin）
 */

export function useLeaveRequestsControllerFindAllAdmin<TData = Awaited<ReturnType<typeof leaveRequestsControllerFindAllAdmin>>, TError = unknown>(
 params?: LeaveRequestsControllerFindAllAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof leaveRequestsControllerFindAllAdmin>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLeaveRequestsControllerFindAllAdminQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary 承認
 */
export const leaveRequestsControllerApprove = (
    id: string,
 signal?: AbortSignal
) => {


      return httpRequest<ActionMessageResponseDto>(
      {url: `/api/v1/admin/leave-requests/${id}/approve`, method: 'POST', signal
    },
      );
    }



export const getLeaveRequestsControllerApproveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof leaveRequestsControllerApprove>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof leaveRequestsControllerApprove>>, TError,{id: string}, TContext> => {

const mutationKey = ['leaveRequestsControllerApprove'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof leaveRequestsControllerApprove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  leaveRequestsControllerApprove(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LeaveRequestsControllerApproveMutationResult = NonNullable<Awaited<ReturnType<typeof leaveRequestsControllerApprove>>>

    export type LeaveRequestsControllerApproveMutationError = unknown

    /**
 * @summary 承認
 */
export const useLeaveRequestsControllerApprove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof leaveRequestsControllerApprove>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof leaveRequestsControllerApprove>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getLeaveRequestsControllerApproveMutationOptions(options), queryClient);
    }
    /**
 * @summary 差し戻し
 */
export const leaveRequestsControllerReject = (
    id: string,
 signal?: AbortSignal
) => {


      return httpRequest<ActionMessageResponseDto>(
      {url: `/api/v1/admin/leave-requests/${id}/reject`, method: 'POST', signal
    },
      );
    }



export const getLeaveRequestsControllerRejectMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof leaveRequestsControllerReject>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof leaveRequestsControllerReject>>, TError,{id: string}, TContext> => {

const mutationKey = ['leaveRequestsControllerReject'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof leaveRequestsControllerReject>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  leaveRequestsControllerReject(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LeaveRequestsControllerRejectMutationResult = NonNullable<Awaited<ReturnType<typeof leaveRequestsControllerReject>>>

    export type LeaveRequestsControllerRejectMutationError = unknown

    /**
 * @summary 差し戻し
 */
export const useLeaveRequestsControllerReject = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof leaveRequestsControllerReject>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof leaveRequestsControllerReject>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getLeaveRequestsControllerRejectMutationOptions(options), queryClient);
    }
