/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateTenantDto,
  CreateTenantResponseDto,
  TenantListResponseDto,
  TenantResponseDto,
  TenantWithCountResponseDto,
  TenantsControllerFindAllParams,
  UpdateTenantDto
} from '../../model';

import { httpRequest } from '../../http-client';




/**
 * @summary テナント作成（初期管理者設定含む）
 */
export const tenantsControllerCreate = (
    createTenantDto: CreateTenantDto,
 signal?: AbortSignal
) => {


      return httpRequest<CreateTenantResponseDto>(
      {url: `/api/v1/tenants`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTenantDto, signal
    },
      );
    }



export const getTenantsControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tenantsControllerCreate>>, TError,{data: CreateTenantDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof tenantsControllerCreate>>, TError,{data: CreateTenantDto}, TContext> => {

const mutationKey = ['tenantsControllerCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tenantsControllerCreate>>, {data: CreateTenantDto}> = (props) => {
          const {data} = props ?? {};

          return  tenantsControllerCreate(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TenantsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof tenantsControllerCreate>>>
    export type TenantsControllerCreateMutationBody = CreateTenantDto
    export type TenantsControllerCreateMutationError = unknown

    /**
 * @summary テナント作成（初期管理者設定含む）
 */
export const useTenantsControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tenantsControllerCreate>>, TError,{data: CreateTenantDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof tenantsControllerCreate>>,
        TError,
        {data: CreateTenantDto},
        TContext
      > => {
      return useMutation(getTenantsControllerCreateMutationOptions(options), queryClient);
    }
    /**
 * @summary テナント一覧
 */
export const tenantsControllerFindAll = (
    params?: TenantsControllerFindAllParams,
 signal?: AbortSignal
) => {


      return httpRequest<TenantListResponseDto>(
      {url: `/api/v1/tenants`, method: 'GET',
        params, signal
    },
      );
    }




export const getTenantsControllerFindAllQueryKey = (params?: TenantsControllerFindAllParams,) => {
    return [
    `/api/v1/tenants`, ...(params ? [params] : [])
    ] as const;
    }


export const getTenantsControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof tenantsControllerFindAll>>, TError = unknown>(params?: TenantsControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tenantsControllerFindAll>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTenantsControllerFindAllQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof tenantsControllerFindAll>>> = ({ signal }) => tenantsControllerFindAll(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof tenantsControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TenantsControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof tenantsControllerFindAll>>>
export type TenantsControllerFindAllQueryError = unknown


export function useTenantsControllerFindAll<TData = Awaited<ReturnType<typeof tenantsControllerFindAll>>, TError = unknown>(
 params: undefined |  TenantsControllerFindAllParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof tenantsControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof tenantsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof tenantsControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTenantsControllerFindAll<TData = Awaited<ReturnType<typeof tenantsControllerFindAll>>, TError = unknown>(
 params?: TenantsControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tenantsControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof tenantsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof tenantsControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTenantsControllerFindAll<TData = Awaited<ReturnType<typeof tenantsControllerFindAll>>, TError = unknown>(
 params?: TenantsControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tenantsControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary テナント一覧
 */

export function useTenantsControllerFindAll<TData = Awaited<ReturnType<typeof tenantsControllerFindAll>>, TError = unknown>(
 params?: TenantsControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tenantsControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTenantsControllerFindAllQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary テナント詳細
 */
export const tenantsControllerFindOne = (
    id: string,
 signal?: AbortSignal
) => {


      return httpRequest<TenantWithCountResponseDto>(
      {url: `/api/v1/tenants/${id}`, method: 'GET', signal
    },
      );
    }




export const getTenantsControllerFindOneQueryKey = (id: string,) => {
    return [
    `/api/v1/tenants/${id}`
    ] as const;
    }


export const getTenantsControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof tenantsControllerFindOne>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tenantsControllerFindOne>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTenantsControllerFindOneQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof tenantsControllerFindOne>>> = ({ signal }) => tenantsControllerFindOne(id, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof tenantsControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TenantsControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof tenantsControllerFindOne>>>
export type TenantsControllerFindOneQueryError = unknown


export function useTenantsControllerFindOne<TData = Awaited<ReturnType<typeof tenantsControllerFindOne>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof tenantsControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof tenantsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof tenantsControllerFindOne>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTenantsControllerFindOne<TData = Awaited<ReturnType<typeof tenantsControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tenantsControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof tenantsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof tenantsControllerFindOne>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTenantsControllerFindOne<TData = Awaited<ReturnType<typeof tenantsControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tenantsControllerFindOne>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary テナント詳細
 */

export function useTenantsControllerFindOne<TData = Awaited<ReturnType<typeof tenantsControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tenantsControllerFindOne>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTenantsControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary テナント更新
 */
export const tenantsControllerUpdate = (
    id: string,
    updateTenantDto: UpdateTenantDto,
 signal?: AbortSignal
) => {


      return httpRequest<TenantResponseDto>(
      {url: `/api/v1/tenants/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateTenantDto, signal
    },
      );
    }



export const getTenantsControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tenantsControllerUpdate>>, TError,{id: string;data: UpdateTenantDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof tenantsControllerUpdate>>, TError,{id: string;data: UpdateTenantDto}, TContext> => {

const mutationKey = ['tenantsControllerUpdate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tenantsControllerUpdate>>, {id: string;data: UpdateTenantDto}> = (props) => {
          const {id,data} = props ?? {};

          return  tenantsControllerUpdate(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TenantsControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof tenantsControllerUpdate>>>
    export type TenantsControllerUpdateMutationBody = UpdateTenantDto
    export type TenantsControllerUpdateMutationError = unknown

    /**
 * @summary テナント更新
 */
export const useTenantsControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tenantsControllerUpdate>>, TError,{id: string;data: UpdateTenantDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof tenantsControllerUpdate>>,
        TError,
        {id: string;data: UpdateTenantDto},
        TContext
      > => {
      return useMutation(getTenantsControllerUpdateMutationOptions(options), queryClient);
    }
    /**
 * @summary テナント停止
 */
export const tenantsControllerSuspend = (
    id: string,
 signal?: AbortSignal
) => {


      return httpRequest<TenantResponseDto>(
      {url: `/api/v1/tenants/${id}/suspend`, method: 'POST', signal
    },
      );
    }



export const getTenantsControllerSuspendMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tenantsControllerSuspend>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof tenantsControllerSuspend>>, TError,{id: string}, TContext> => {

const mutationKey = ['tenantsControllerSuspend'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tenantsControllerSuspend>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  tenantsControllerSuspend(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TenantsControllerSuspendMutationResult = NonNullable<Awaited<ReturnType<typeof tenantsControllerSuspend>>>

    export type TenantsControllerSuspendMutationError = unknown

    /**
 * @summary テナント停止
 */
export const useTenantsControllerSuspend = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tenantsControllerSuspend>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof tenantsControllerSuspend>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getTenantsControllerSuspendMutationOptions(options), queryClient);
    }
    /**
 * @summary テナント再開
 */
export const tenantsControllerResume = (
    id: string,
 signal?: AbortSignal
) => {


      return httpRequest<TenantResponseDto>(
      {url: `/api/v1/tenants/${id}/resume`, method: 'POST', signal
    },
      );
    }



export const getTenantsControllerResumeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tenantsControllerResume>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof tenantsControllerResume>>, TError,{id: string}, TContext> => {

const mutationKey = ['tenantsControllerResume'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tenantsControllerResume>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  tenantsControllerResume(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TenantsControllerResumeMutationResult = NonNullable<Awaited<ReturnType<typeof tenantsControllerResume>>>

    export type TenantsControllerResumeMutationError = unknown

    /**
 * @summary テナント再開
 */
export const useTenantsControllerResume = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tenantsControllerResume>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof tenantsControllerResume>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getTenantsControllerResumeMutationOptions(options), queryClient);
    }
