/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ClockCorrectionsControllerFindAllAdminParams,
  ClockCorrectionsControllerFindMineParams,
  CreateClockCorrectionDto
} from '../../model';

import { customAxios } from '../../http-client';




/**
 * @summary 打刻修正申請作成
 */
export const clockCorrectionsControllerCreate = (
    createClockCorrectionDto: CreateClockCorrectionDto,
 signal?: AbortSignal
) => {


      return customAxios<void>(
      {url: `/api/v1/clock-corrections`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createClockCorrectionDto, signal
    },
      );
    }



export const getClockCorrectionsControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clockCorrectionsControllerCreate>>, TError,{data: CreateClockCorrectionDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof clockCorrectionsControllerCreate>>, TError,{data: CreateClockCorrectionDto}, TContext> => {

const mutationKey = ['clockCorrectionsControllerCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof clockCorrectionsControllerCreate>>, {data: CreateClockCorrectionDto}> = (props) => {
          const {data} = props ?? {};

          return  clockCorrectionsControllerCreate(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClockCorrectionsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof clockCorrectionsControllerCreate>>>
    export type ClockCorrectionsControllerCreateMutationBody = CreateClockCorrectionDto
    export type ClockCorrectionsControllerCreateMutationError = unknown

    /**
 * @summary 打刻修正申請作成
 */
export const useClockCorrectionsControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clockCorrectionsControllerCreate>>, TError,{data: CreateClockCorrectionDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof clockCorrectionsControllerCreate>>,
        TError,
        {data: CreateClockCorrectionDto},
        TContext
      > => {
      return useMutation(getClockCorrectionsControllerCreateMutationOptions(options), queryClient);
    }
    /**
 * @summary 自身の修正申請一覧
 */
export const clockCorrectionsControllerFindMine = (
    params: ClockCorrectionsControllerFindMineParams,
 signal?: AbortSignal
) => {


      return customAxios<void>(
      {url: `/api/v1/clock-corrections`, method: 'GET',
        params, signal
    },
      );
    }




export const getClockCorrectionsControllerFindMineQueryKey = (params?: ClockCorrectionsControllerFindMineParams,) => {
    return [
    `/api/v1/clock-corrections`, ...(params ? [params] : [])
    ] as const;
    }


export const getClockCorrectionsControllerFindMineQueryOptions = <TData = Awaited<ReturnType<typeof clockCorrectionsControllerFindMine>>, TError = unknown>(params: ClockCorrectionsControllerFindMineParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clockCorrectionsControllerFindMine>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getClockCorrectionsControllerFindMineQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof clockCorrectionsControllerFindMine>>> = ({ signal }) => clockCorrectionsControllerFindMine(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof clockCorrectionsControllerFindMine>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ClockCorrectionsControllerFindMineQueryResult = NonNullable<Awaited<ReturnType<typeof clockCorrectionsControllerFindMine>>>
export type ClockCorrectionsControllerFindMineQueryError = unknown


export function useClockCorrectionsControllerFindMine<TData = Awaited<ReturnType<typeof clockCorrectionsControllerFindMine>>, TError = unknown>(
 params: ClockCorrectionsControllerFindMineParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof clockCorrectionsControllerFindMine>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof clockCorrectionsControllerFindMine>>,
          TError,
          Awaited<ReturnType<typeof clockCorrectionsControllerFindMine>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useClockCorrectionsControllerFindMine<TData = Awaited<ReturnType<typeof clockCorrectionsControllerFindMine>>, TError = unknown>(
 params: ClockCorrectionsControllerFindMineParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clockCorrectionsControllerFindMine>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof clockCorrectionsControllerFindMine>>,
          TError,
          Awaited<ReturnType<typeof clockCorrectionsControllerFindMine>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useClockCorrectionsControllerFindMine<TData = Awaited<ReturnType<typeof clockCorrectionsControllerFindMine>>, TError = unknown>(
 params: ClockCorrectionsControllerFindMineParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clockCorrectionsControllerFindMine>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 自身の修正申請一覧
 */

export function useClockCorrectionsControllerFindMine<TData = Awaited<ReturnType<typeof clockCorrectionsControllerFindMine>>, TError = unknown>(
 params: ClockCorrectionsControllerFindMineParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clockCorrectionsControllerFindMine>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getClockCorrectionsControllerFindMineQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary テナント内申請一覧（tenant_admin）
 */
export const clockCorrectionsControllerFindAllAdmin = (
    params: ClockCorrectionsControllerFindAllAdminParams,
 signal?: AbortSignal
) => {


      return customAxios<void>(
      {url: `/api/v1/admin/clock-corrections`, method: 'GET',
        params, signal
    },
      );
    }




export const getClockCorrectionsControllerFindAllAdminQueryKey = (params?: ClockCorrectionsControllerFindAllAdminParams,) => {
    return [
    `/api/v1/admin/clock-corrections`, ...(params ? [params] : [])
    ] as const;
    }


export const getClockCorrectionsControllerFindAllAdminQueryOptions = <TData = Awaited<ReturnType<typeof clockCorrectionsControllerFindAllAdmin>>, TError = unknown>(params: ClockCorrectionsControllerFindAllAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clockCorrectionsControllerFindAllAdmin>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getClockCorrectionsControllerFindAllAdminQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof clockCorrectionsControllerFindAllAdmin>>> = ({ signal }) => clockCorrectionsControllerFindAllAdmin(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof clockCorrectionsControllerFindAllAdmin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ClockCorrectionsControllerFindAllAdminQueryResult = NonNullable<Awaited<ReturnType<typeof clockCorrectionsControllerFindAllAdmin>>>
export type ClockCorrectionsControllerFindAllAdminQueryError = unknown


export function useClockCorrectionsControllerFindAllAdmin<TData = Awaited<ReturnType<typeof clockCorrectionsControllerFindAllAdmin>>, TError = unknown>(
 params: ClockCorrectionsControllerFindAllAdminParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof clockCorrectionsControllerFindAllAdmin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof clockCorrectionsControllerFindAllAdmin>>,
          TError,
          Awaited<ReturnType<typeof clockCorrectionsControllerFindAllAdmin>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useClockCorrectionsControllerFindAllAdmin<TData = Awaited<ReturnType<typeof clockCorrectionsControllerFindAllAdmin>>, TError = unknown>(
 params: ClockCorrectionsControllerFindAllAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clockCorrectionsControllerFindAllAdmin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof clockCorrectionsControllerFindAllAdmin>>,
          TError,
          Awaited<ReturnType<typeof clockCorrectionsControllerFindAllAdmin>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useClockCorrectionsControllerFindAllAdmin<TData = Awaited<ReturnType<typeof clockCorrectionsControllerFindAllAdmin>>, TError = unknown>(
 params: ClockCorrectionsControllerFindAllAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clockCorrectionsControllerFindAllAdmin>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary テナント内申請一覧（tenant_admin）
 */

export function useClockCorrectionsControllerFindAllAdmin<TData = Awaited<ReturnType<typeof clockCorrectionsControllerFindAllAdmin>>, TError = unknown>(
 params: ClockCorrectionsControllerFindAllAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clockCorrectionsControllerFindAllAdmin>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getClockCorrectionsControllerFindAllAdminQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary 承認
 */
export const clockCorrectionsControllerApprove = (
    id: string,
 signal?: AbortSignal
) => {


      return customAxios<void>(
      {url: `/api/v1/admin/clock-corrections/${id}/approve`, method: 'POST', signal
    },
      );
    }



export const getClockCorrectionsControllerApproveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clockCorrectionsControllerApprove>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof clockCorrectionsControllerApprove>>, TError,{id: string}, TContext> => {

const mutationKey = ['clockCorrectionsControllerApprove'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof clockCorrectionsControllerApprove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  clockCorrectionsControllerApprove(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClockCorrectionsControllerApproveMutationResult = NonNullable<Awaited<ReturnType<typeof clockCorrectionsControllerApprove>>>

    export type ClockCorrectionsControllerApproveMutationError = unknown

    /**
 * @summary 承認
 */
export const useClockCorrectionsControllerApprove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clockCorrectionsControllerApprove>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof clockCorrectionsControllerApprove>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getClockCorrectionsControllerApproveMutationOptions(options), queryClient);
    }
    /**
 * @summary 差し戻し
 */
export const clockCorrectionsControllerReject = (
    id: string,
 signal?: AbortSignal
) => {


      return customAxios<void>(
      {url: `/api/v1/admin/clock-corrections/${id}/reject`, method: 'POST', signal
    },
      );
    }



export const getClockCorrectionsControllerRejectMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clockCorrectionsControllerReject>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof clockCorrectionsControllerReject>>, TError,{id: string}, TContext> => {

const mutationKey = ['clockCorrectionsControllerReject'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof clockCorrectionsControllerReject>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  clockCorrectionsControllerReject(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClockCorrectionsControllerRejectMutationResult = NonNullable<Awaited<ReturnType<typeof clockCorrectionsControllerReject>>>

    export type ClockCorrectionsControllerRejectMutationError = unknown

    /**
 * @summary 差し戻し
 */
export const useClockCorrectionsControllerReject = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clockCorrectionsControllerReject>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof clockCorrectionsControllerReject>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getClockCorrectionsControllerRejectMutationOptions(options), queryClient);
    }
