/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */
import type { AttendanceEmployeeResponseDto } from './attendanceEmployeeResponseDto';
import type { AttendanceListItemResponseDtoClockIn } from './attendanceListItemResponseDtoClockIn';
import type { AttendanceListItemResponseDtoClockOut } from './attendanceListItemResponseDtoClockOut';
import type { AttendanceListItemResponseDtoStatus } from './attendanceListItemResponseDtoStatus';
import type { BreakRecordResponseDto } from './breakRecordResponseDto';

export interface AttendanceListItemResponseDto {
  id: string;
  tenantId: string;
  employeeId: string;
  date: string;
  /** @nullable */
  clockIn: AttendanceListItemResponseDtoClockIn;
  /** @nullable */
  clockOut: AttendanceListItemResponseDtoClockOut;
  status: AttendanceListItemResponseDtoStatus;
  isOvernight: boolean;
  createdAt: string;
  updatedAt: string;
  breakRecords: BreakRecordResponseDto[];
  employee: AttendanceEmployeeResponseDto;
}
