/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */

export interface AttendanceSummaryResponseDto {
  year: number;
  month: number;
  totalWorkMinutes: number;
  totalBreakMinutes: number;
  totalOvertimeMinutes: number;
  totalNightMinutes: number;
  presentDays: number;
  absentDays: number;
  holidayDays: number;
}
