/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */

export type AttendanceControllerFindAllAdminParams = {
employee_id?: string;
year?: number;
month?: number;
page?: number;
limit?: number;
};
