/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */
import type { AttendanceResponseDtoClockIn } from './attendanceResponseDtoClockIn';
import type { AttendanceResponseDtoClockOut } from './attendanceResponseDtoClockOut';
import type { AttendanceResponseDtoStatus } from './attendanceResponseDtoStatus';
import type { BreakRecordResponseDto } from './breakRecordResponseDto';

export interface AttendanceResponseDto {
  id: string;
  tenantId: string;
  employeeId: string;
  date: string;
  /** @nullable */
  clockIn: AttendanceResponseDtoClockIn;
  /** @nullable */
  clockOut: AttendanceResponseDtoClockOut;
  status: AttendanceResponseDtoStatus;
  isOvernight: boolean;
  createdAt: string;
  updatedAt: string;
  breakRecords: BreakRecordResponseDto[];
}
