/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */

export type AuditLogsControllerFindAllSystemParams = {
action: string;
actor_id: string;
from: string;
to: string;
page: number;
limit: number;
};
