/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */
import type { AuditLogActorResponseDto } from './auditLogActorResponseDto';
import type { AuditLogResponseDtoDetail } from './auditLogResponseDtoDetail';
import type { AuditLogResponseDtoTargetId } from './auditLogResponseDtoTargetId';
import type { AuditLogResponseDtoTenantId } from './auditLogResponseDtoTenantId';

export interface AuditLogResponseDto {
  id: string;
  /** @nullable */
  tenantId: AuditLogResponseDtoTenantId;
  actorId: string;
  action: string;
  targetType: string;
  /** @nullable */
  targetId: AuditLogResponseDtoTargetId;
  /** @nullable */
  detail: AuditLogResponseDtoDetail;
  createdAt: string;
  actor: AuditLogActorResponseDto;
}
