/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */
import type { BreakRecordResponseDtoEndTime } from './breakRecordResponseDtoEndTime';

export interface BreakRecordResponseDto {
  id: string;
  attendanceId: string;
  startTime: string;
  /** @nullable */
  endTime: BreakRecordResponseDtoEndTime;
}
