/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */
import type { AttendanceEmployeeResponseDto } from './attendanceEmployeeResponseDto';
import type { AttendanceResponseDto } from './attendanceResponseDto';
import type { ClockCorrectionAdminItemResponseDtoCorrectedClockIn } from './clockCorrectionAdminItemResponseDtoCorrectedClockIn';
import type { ClockCorrectionAdminItemResponseDtoCorrectedClockOut } from './clockCorrectionAdminItemResponseDtoCorrectedClockOut';
import type { ClockCorrectionAdminItemResponseDtoOriginalClockIn } from './clockCorrectionAdminItemResponseDtoOriginalClockIn';
import type { ClockCorrectionAdminItemResponseDtoOriginalClockOut } from './clockCorrectionAdminItemResponseDtoOriginalClockOut';
import type { ClockCorrectionAdminItemResponseDtoReviewedAt } from './clockCorrectionAdminItemResponseDtoReviewedAt';
import type { ClockCorrectionAdminItemResponseDtoReviewedBy } from './clockCorrectionAdminItemResponseDtoReviewedBy';
import type { ClockCorrectionAdminItemResponseDtoStatus } from './clockCorrectionAdminItemResponseDtoStatus';

export interface ClockCorrectionAdminItemResponseDto {
  id: string;
  tenantId: string;
  attendanceId: string;
  requestedBy: string;
  /** @nullable */
  originalClockIn: ClockCorrectionAdminItemResponseDtoOriginalClockIn;
  /** @nullable */
  originalClockOut: ClockCorrectionAdminItemResponseDtoOriginalClockOut;
  /** @nullable */
  correctedClockIn: ClockCorrectionAdminItemResponseDtoCorrectedClockIn;
  /** @nullable */
  correctedClockOut: ClockCorrectionAdminItemResponseDtoCorrectedClockOut;
  reason: string;
  status: ClockCorrectionAdminItemResponseDtoStatus;
  /** @nullable */
  reviewedBy: ClockCorrectionAdminItemResponseDtoReviewedBy;
  /** @nullable */
  reviewedAt: ClockCorrectionAdminItemResponseDtoReviewedAt;
  createdAt: string;
  attendance: AttendanceResponseDto;
  employee: AttendanceEmployeeResponseDto;
}
