/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */
import type { ClockCorrectionResponseDtoCorrectedClockIn } from './clockCorrectionResponseDtoCorrectedClockIn';
import type { ClockCorrectionResponseDtoCorrectedClockOut } from './clockCorrectionResponseDtoCorrectedClockOut';
import type { ClockCorrectionResponseDtoOriginalClockIn } from './clockCorrectionResponseDtoOriginalClockIn';
import type { ClockCorrectionResponseDtoOriginalClockOut } from './clockCorrectionResponseDtoOriginalClockOut';
import type { ClockCorrectionResponseDtoReviewedAt } from './clockCorrectionResponseDtoReviewedAt';
import type { ClockCorrectionResponseDtoReviewedBy } from './clockCorrectionResponseDtoReviewedBy';
import type { ClockCorrectionResponseDtoStatus } from './clockCorrectionResponseDtoStatus';

export interface ClockCorrectionResponseDto {
  id: string;
  tenantId: string;
  attendanceId: string;
  requestedBy: string;
  /** @nullable */
  originalClockIn: ClockCorrectionResponseDtoOriginalClockIn;
  /** @nullable */
  originalClockOut: ClockCorrectionResponseDtoOriginalClockOut;
  /** @nullable */
  correctedClockIn: ClockCorrectionResponseDtoCorrectedClockIn;
  /** @nullable */
  correctedClockOut: ClockCorrectionResponseDtoCorrectedClockOut;
  reason: string;
  status: ClockCorrectionResponseDtoStatus;
  /** @nullable */
  reviewedBy: ClockCorrectionResponseDtoReviewedBy;
  /** @nullable */
  reviewedAt: ClockCorrectionResponseDtoReviewedAt;
  createdAt: string;
}
