/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */
import type { AttendanceResponseDto } from './attendanceResponseDto';
import type { ClockCorrectionMineItemResponseDtoCorrectedClockIn } from './clockCorrectionMineItemResponseDtoCorrectedClockIn';
import type { ClockCorrectionMineItemResponseDtoCorrectedClockOut } from './clockCorrectionMineItemResponseDtoCorrectedClockOut';
import type { ClockCorrectionMineItemResponseDtoOriginalClockIn } from './clockCorrectionMineItemResponseDtoOriginalClockIn';
import type { ClockCorrectionMineItemResponseDtoOriginalClockOut } from './clockCorrectionMineItemResponseDtoOriginalClockOut';
import type { ClockCorrectionMineItemResponseDtoReviewedAt } from './clockCorrectionMineItemResponseDtoReviewedAt';
import type { ClockCorrectionMineItemResponseDtoReviewedBy } from './clockCorrectionMineItemResponseDtoReviewedBy';
import type { ClockCorrectionMineItemResponseDtoStatus } from './clockCorrectionMineItemResponseDtoStatus';

export interface ClockCorrectionMineItemResponseDto {
  id: string;
  tenantId: string;
  attendanceId: string;
  requestedBy: string;
  /** @nullable */
  originalClockIn: ClockCorrectionMineItemResponseDtoOriginalClockIn;
  /** @nullable */
  originalClockOut: ClockCorrectionMineItemResponseDtoOriginalClockOut;
  /** @nullable */
  correctedClockIn: ClockCorrectionMineItemResponseDtoCorrectedClockIn;
  /** @nullable */
  correctedClockOut: ClockCorrectionMineItemResponseDtoCorrectedClockOut;
  reason: string;
  status: ClockCorrectionMineItemResponseDtoStatus;
  /** @nullable */
  reviewedBy: ClockCorrectionMineItemResponseDtoReviewedBy;
  /** @nullable */
  reviewedAt: ClockCorrectionMineItemResponseDtoReviewedAt;
  createdAt: string;
  attendance: AttendanceResponseDto;
}
