/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */
import type { ClosingCloserResponseDto } from './closingCloserResponseDto';
import type { ClosingRecordListItemResponseDtoStatus } from './closingRecordListItemResponseDtoStatus';

export interface ClosingRecordListItemResponseDto {
  id: string;
  tenantId: string;
  yearMonth: string;
  closedBy: string;
  closedAt: string;
  status: ClosingRecordListItemResponseDtoStatus;
  closer: ClosingCloserResponseDto;
}
