/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */

export type ClosingRecordResponseDtoStatus = typeof ClosingRecordResponseDtoStatus[keyof typeof ClosingRecordResponseDtoStatus];


export const ClosingRecordResponseDtoStatus = {
  closed: 'closed',
  reopened: 'reopened',
} as const;
