/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */

export interface CreateEmployeeDto {
  employeeNumber: string;
  name: string;
  joinedAt: string;
  /** 紐付けるユーザーID */
  userId?: string;
  /** 部署ID */
  departmentId?: string;
  /** 勤務形態ID */
  workPatternId?: string;
}
