/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */
import type { CreateLeaveRequestDtoLeaveType } from './createLeaveRequestDtoLeaveType';

export interface CreateLeaveRequestDto {
  leaveType: CreateLeaveRequestDtoLeaveType;
  startDate: string;
  endDate: string;
  reason?: string;
}
