/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */

export type CreateLeaveRequestDtoLeaveType = typeof CreateLeaveRequestDtoLeaveType[keyof typeof CreateLeaveRequestDtoLeaveType];


export const CreateLeaveRequestDtoLeaveType = {
  paid: 'paid',
  unpaid: 'unpaid',
  sick: 'sick',
  other: 'other',
} as const;
