/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */

export interface CreateClockCorrectionDto {
  /** 対象勤怠レコードID */
  attendanceId: string;
  /** 修正後出勤時刻（ISO8601） */
  correctedClockIn?: string;
  /** 修正後退勤時刻（ISO8601） */
  correctedClockOut?: string;
  /** 修正理由 */
  reason: string;
}
