/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */

export interface CreateWorkPatternDto {
  name: string;
  /** 所定開始時刻（HH:MM:SS） */
  startTime: string;
  /** 所定終了時刻（HH:MM:SS） */
  endTime: string;
  /** 所定休憩時間（分） */
  breakMinutes?: number;
}
