/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */
import type { TenantResponseDto } from './tenantResponseDto';
import type { UserResponseDto } from './userResponseDto';

export interface CreateTenantResponseDto {
  tenant: TenantResponseDto;
  adminUser: UserResponseDto;
}
