/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */
import type { EmployeeResponseDto } from './employeeResponseDto';

export interface EmployeeListResponseDto {
  data: EmployeeResponseDto[];
  total: number;
  page: number;
  limit: number;
}
