/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */
import type { DepartmentResponseDto } from './departmentResponseDto';
import type { EmployeeResponseDtoDepartmentId } from './employeeResponseDtoDepartmentId';
import type { EmployeeResponseDtoUserId } from './employeeResponseDtoUserId';
import type { EmployeeResponseDtoWorkPatternId } from './employeeResponseDtoWorkPatternId';
import type { EmployeeUserResponseDto } from './employeeUserResponseDto';
import type { WorkPatternResponseDto } from './workPatternResponseDto';

export interface EmployeeResponseDto {
  id: string;
  tenantId: string;
  /** @nullable */
  userId: EmployeeResponseDtoUserId;
  employeeNumber: string;
  name: string;
  /** @nullable */
  departmentId: EmployeeResponseDtoDepartmentId;
  /** @nullable */
  workPatternId: EmployeeResponseDtoWorkPatternId;
  joinedAt: string;
  createdAt: string;
  department: DepartmentResponseDto | null;
  workPattern: WorkPatternResponseDto | null;
  user: EmployeeUserResponseDto | null;
}
