/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */
import type { EmployeeUserResponseDtoRole } from './employeeUserResponseDtoRole';

export interface EmployeeUserResponseDto {
  id: string;
  email: string;
  name: string;
  role?: EmployeeUserResponseDtoRole;
}
