/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */
import type { LeaveRequestResponseDtoLeaveType } from './leaveRequestResponseDtoLeaveType';
import type { LeaveRequestResponseDtoReason } from './leaveRequestResponseDtoReason';
import type { LeaveRequestResponseDtoReviewedAt } from './leaveRequestResponseDtoReviewedAt';
import type { LeaveRequestResponseDtoReviewedBy } from './leaveRequestResponseDtoReviewedBy';
import type { LeaveRequestResponseDtoStatus } from './leaveRequestResponseDtoStatus';

export interface LeaveRequestResponseDto {
  id: string;
  tenantId: string;
  employeeId: string;
  leaveType: LeaveRequestResponseDtoLeaveType;
  startDate: string;
  endDate: string;
  /** @nullable */
  reason: LeaveRequestResponseDtoReason;
  status: LeaveRequestResponseDtoStatus;
  /** @nullable */
  reviewedBy: LeaveRequestResponseDtoReviewedBy;
  /** @nullable */
  reviewedAt: LeaveRequestResponseDtoReviewedAt;
  createdAt: string;
}
