/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */

export type LeaveRequestAdminItemResponseDtoStatus = typeof LeaveRequestAdminItemResponseDtoStatus[keyof typeof LeaveRequestAdminItemResponseDtoStatus];


export const LeaveRequestAdminItemResponseDtoStatus = {
  pending: 'pending',
  approved: 'approved',
  rejected: 'rejected',
} as const;
