/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */
import type { AttendanceEmployeeResponseDto } from './attendanceEmployeeResponseDto';
import type { LeaveRequestAdminItemResponseDtoLeaveType } from './leaveRequestAdminItemResponseDtoLeaveType';
import type { LeaveRequestAdminItemResponseDtoReason } from './leaveRequestAdminItemResponseDtoReason';
import type { LeaveRequestAdminItemResponseDtoReviewedAt } from './leaveRequestAdminItemResponseDtoReviewedAt';
import type { LeaveRequestAdminItemResponseDtoReviewedBy } from './leaveRequestAdminItemResponseDtoReviewedBy';
import type { LeaveRequestAdminItemResponseDtoStatus } from './leaveRequestAdminItemResponseDtoStatus';

export interface LeaveRequestAdminItemResponseDto {
  id: string;
  tenantId: string;
  employeeId: string;
  leaveType: LeaveRequestAdminItemResponseDtoLeaveType;
  startDate: string;
  endDate: string;
  /** @nullable */
  reason: LeaveRequestAdminItemResponseDtoReason;
  status: LeaveRequestAdminItemResponseDtoStatus;
  /** @nullable */
  reviewedBy: LeaveRequestAdminItemResponseDtoReviewedBy;
  /** @nullable */
  reviewedAt: LeaveRequestAdminItemResponseDtoReviewedAt;
  createdAt: string;
  employee: AttendanceEmployeeResponseDto;
}
