/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */
import type { MeResponseDtoRole } from './meResponseDtoRole';
import type { MeResponseDtoTenantId } from './meResponseDtoTenantId';

export interface MeResponseDto {
  id: string;
  email: string;
  name: string;
  role: MeResponseDtoRole;
  /** @nullable */
  tenantId: MeResponseDtoTenantId;
  isActive: boolean;
  createdAt: string;
}
