/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */

export type MeResponseDtoRole = typeof MeResponseDtoRole[keyof typeof MeResponseDtoRole];


export const MeResponseDtoRole = {
  system_admin: 'system_admin',
  tenant_admin: 'tenant_admin',
  tenant_user: 'tenant_user',
} as const;
