/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */
import type { TenantUserCountResponseDto } from './tenantUserCountResponseDto';
import type { TenantWithCountResponseDtoStatus } from './tenantWithCountResponseDtoStatus';

export interface TenantWithCountResponseDto {
  id: string;
  name: string;
  status: TenantWithCountResponseDtoStatus;
  createdAt: string;
  updatedAt: string;
  _count: TenantUserCountResponseDto;
}
