/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */

export type UserResponseDtoRole = typeof UserResponseDtoRole[keyof typeof UserResponseDtoRole];


export const UserResponseDtoRole = {
  system_admin: 'system_admin',
  tenant_admin: 'tenant_admin',
  tenant_user: 'tenant_user',
} as const;
