/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */
import type { UserResponseDtoRole } from './userResponseDtoRole';
import type { UserResponseDtoTenantId } from './userResponseDtoTenantId';

export interface UserResponseDto {
  id: string;
  email: string;
  name: string;
  role: UserResponseDtoRole;
  isActive: boolean;
  createdAt: string;
  firebaseUid: string;
  /** @nullable */
  tenantId: UserResponseDtoTenantId;
  updatedAt: string;
}
