/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AttendanceControllerFindAllAdminParams,
  AttendanceControllerFindMineParams,
  AttendanceControllerGetAdminSummaryParams,
  AttendanceControllerGetMySummaryParams,
  AttendanceListResponseDto,
  AttendanceResponseDto,
  AttendanceSummaryResponseDto,
  BreakRecordResponseDto
} from '../../model';

import { httpRequest } from '../../http-client';




/**
 * @summary 出勤打刻
 */
export const attendanceControllerClockIn = (

 signal?: AbortSignal
) => {


      return httpRequest<AttendanceResponseDto>(
      {url: `/api/v1/attendance/clock-in`, method: 'POST', signal
    },
      );
    }



export const getAttendanceControllerClockInMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof attendanceControllerClockIn>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof attendanceControllerClockIn>>, TError,void, TContext> => {

const mutationKey = ['attendanceControllerClockIn'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof attendanceControllerClockIn>>, void> = () => {


          return  attendanceControllerClockIn()
        }






  return  { mutationFn, ...mutationOptions }}

    export type AttendanceControllerClockInMutationResult = NonNullable<Awaited<ReturnType<typeof attendanceControllerClockIn>>>

    export type AttendanceControllerClockInMutationError = unknown

    /**
 * @summary 出勤打刻
 */
export const useAttendanceControllerClockIn = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof attendanceControllerClockIn>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof attendanceControllerClockIn>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAttendanceControllerClockInMutationOptions(options), queryClient);
    }
    /**
 * @summary 退勤打刻
 */
export const attendanceControllerClockOut = (

 signal?: AbortSignal
) => {


      return httpRequest<AttendanceResponseDto>(
      {url: `/api/v1/attendance/clock-out`, method: 'POST', signal
    },
      );
    }



export const getAttendanceControllerClockOutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof attendanceControllerClockOut>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof attendanceControllerClockOut>>, TError,void, TContext> => {

const mutationKey = ['attendanceControllerClockOut'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof attendanceControllerClockOut>>, void> = () => {


          return  attendanceControllerClockOut()
        }






  return  { mutationFn, ...mutationOptions }}

    export type AttendanceControllerClockOutMutationResult = NonNullable<Awaited<ReturnType<typeof attendanceControllerClockOut>>>

    export type AttendanceControllerClockOutMutationError = unknown

    /**
 * @summary 退勤打刻
 */
export const useAttendanceControllerClockOut = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof attendanceControllerClockOut>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof attendanceControllerClockOut>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAttendanceControllerClockOutMutationOptions(options), queryClient);
    }
    /**
 * @summary 休憩開始
 */
export const attendanceControllerBreakStart = (

 signal?: AbortSignal
) => {


      return httpRequest<BreakRecordResponseDto>(
      {url: `/api/v1/attendance/break/start`, method: 'POST', signal
    },
      );
    }



export const getAttendanceControllerBreakStartMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof attendanceControllerBreakStart>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof attendanceControllerBreakStart>>, TError,void, TContext> => {

const mutationKey = ['attendanceControllerBreakStart'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof attendanceControllerBreakStart>>, void> = () => {


          return  attendanceControllerBreakStart()
        }






  return  { mutationFn, ...mutationOptions }}

    export type AttendanceControllerBreakStartMutationResult = NonNullable<Awaited<ReturnType<typeof attendanceControllerBreakStart>>>

    export type AttendanceControllerBreakStartMutationError = unknown

    /**
 * @summary 休憩開始
 */
export const useAttendanceControllerBreakStart = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof attendanceControllerBreakStart>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof attendanceControllerBreakStart>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAttendanceControllerBreakStartMutationOptions(options), queryClient);
    }
    /**
 * @summary 休憩終了
 */
export const attendanceControllerBreakEnd = (

 signal?: AbortSignal
) => {


      return httpRequest<BreakRecordResponseDto>(
      {url: `/api/v1/attendance/break/end`, method: 'POST', signal
    },
      );
    }



export const getAttendanceControllerBreakEndMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof attendanceControllerBreakEnd>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof attendanceControllerBreakEnd>>, TError,void, TContext> => {

const mutationKey = ['attendanceControllerBreakEnd'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof attendanceControllerBreakEnd>>, void> = () => {


          return  attendanceControllerBreakEnd()
        }






  return  { mutationFn, ...mutationOptions }}

    export type AttendanceControllerBreakEndMutationResult = NonNullable<Awaited<ReturnType<typeof attendanceControllerBreakEnd>>>

    export type AttendanceControllerBreakEndMutationError = unknown

    /**
 * @summary 休憩終了
 */
export const useAttendanceControllerBreakEnd = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof attendanceControllerBreakEnd>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof attendanceControllerBreakEnd>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAttendanceControllerBreakEndMutationOptions(options), queryClient);
    }
    /**
 * @summary 本日の勤怠状態取得
 */
export const attendanceControllerGetToday = (

 signal?: AbortSignal
) => {


      return httpRequest<AttendanceResponseDto>(
      {url: `/api/v1/attendance/today`, method: 'GET', signal
    },
      );
    }




export const getAttendanceControllerGetTodayQueryKey = () => {
    return [
    `/api/v1/attendance/today`
    ] as const;
    }


export const getAttendanceControllerGetTodayQueryOptions = <TData = Awaited<ReturnType<typeof attendanceControllerGetToday>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerGetToday>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAttendanceControllerGetTodayQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof attendanceControllerGetToday>>> = ({ signal }) => attendanceControllerGetToday(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerGetToday>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AttendanceControllerGetTodayQueryResult = NonNullable<Awaited<ReturnType<typeof attendanceControllerGetToday>>>
export type AttendanceControllerGetTodayQueryError = unknown


export function useAttendanceControllerGetToday<TData = Awaited<ReturnType<typeof attendanceControllerGetToday>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerGetToday>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof attendanceControllerGetToday>>,
          TError,
          Awaited<ReturnType<typeof attendanceControllerGetToday>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAttendanceControllerGetToday<TData = Awaited<ReturnType<typeof attendanceControllerGetToday>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerGetToday>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof attendanceControllerGetToday>>,
          TError,
          Awaited<ReturnType<typeof attendanceControllerGetToday>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAttendanceControllerGetToday<TData = Awaited<ReturnType<typeof attendanceControllerGetToday>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerGetToday>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 本日の勤怠状態取得
 */

export function useAttendanceControllerGetToday<TData = Awaited<ReturnType<typeof attendanceControllerGetToday>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerGetToday>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAttendanceControllerGetTodayQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary 自身の勤怠一覧（月指定）
 */
export const attendanceControllerFindMine = (
    params?: AttendanceControllerFindMineParams,
 signal?: AbortSignal
) => {


      return httpRequest<AttendanceListResponseDto>(
      {url: `/api/v1/attendance`, method: 'GET',
        params, signal
    },
      );
    }




export const getAttendanceControllerFindMineQueryKey = (params?: AttendanceControllerFindMineParams,) => {
    return [
    `/api/v1/attendance`, ...(params ? [params] : [])
    ] as const;
    }


export const getAttendanceControllerFindMineQueryOptions = <TData = Awaited<ReturnType<typeof attendanceControllerFindMine>>, TError = unknown>(params?: AttendanceControllerFindMineParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerFindMine>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAttendanceControllerFindMineQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof attendanceControllerFindMine>>> = ({ signal }) => attendanceControllerFindMine(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerFindMine>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AttendanceControllerFindMineQueryResult = NonNullable<Awaited<ReturnType<typeof attendanceControllerFindMine>>>
export type AttendanceControllerFindMineQueryError = unknown


export function useAttendanceControllerFindMine<TData = Awaited<ReturnType<typeof attendanceControllerFindMine>>, TError = unknown>(
 params: undefined |  AttendanceControllerFindMineParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerFindMine>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof attendanceControllerFindMine>>,
          TError,
          Awaited<ReturnType<typeof attendanceControllerFindMine>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAttendanceControllerFindMine<TData = Awaited<ReturnType<typeof attendanceControllerFindMine>>, TError = unknown>(
 params?: AttendanceControllerFindMineParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerFindMine>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof attendanceControllerFindMine>>,
          TError,
          Awaited<ReturnType<typeof attendanceControllerFindMine>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAttendanceControllerFindMine<TData = Awaited<ReturnType<typeof attendanceControllerFindMine>>, TError = unknown>(
 params?: AttendanceControllerFindMineParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerFindMine>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 自身の勤怠一覧（月指定）
 */

export function useAttendanceControllerFindMine<TData = Awaited<ReturnType<typeof attendanceControllerFindMine>>, TError = unknown>(
 params?: AttendanceControllerFindMineParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerFindMine>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAttendanceControllerFindMineQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary 自身の月次集計
 */
export const attendanceControllerGetMySummary = (
    params: AttendanceControllerGetMySummaryParams,
 signal?: AbortSignal
) => {


      return httpRequest<AttendanceSummaryResponseDto>(
      {url: `/api/v1/attendance/summary`, method: 'GET',
        params, signal
    },
      );
    }




export const getAttendanceControllerGetMySummaryQueryKey = (params?: AttendanceControllerGetMySummaryParams,) => {
    return [
    `/api/v1/attendance/summary`, ...(params ? [params] : [])
    ] as const;
    }


export const getAttendanceControllerGetMySummaryQueryOptions = <TData = Awaited<ReturnType<typeof attendanceControllerGetMySummary>>, TError = unknown>(params: AttendanceControllerGetMySummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerGetMySummary>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAttendanceControllerGetMySummaryQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof attendanceControllerGetMySummary>>> = ({ signal }) => attendanceControllerGetMySummary(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerGetMySummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AttendanceControllerGetMySummaryQueryResult = NonNullable<Awaited<ReturnType<typeof attendanceControllerGetMySummary>>>
export type AttendanceControllerGetMySummaryQueryError = unknown


export function useAttendanceControllerGetMySummary<TData = Awaited<ReturnType<typeof attendanceControllerGetMySummary>>, TError = unknown>(
 params: AttendanceControllerGetMySummaryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerGetMySummary>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof attendanceControllerGetMySummary>>,
          TError,
          Awaited<ReturnType<typeof attendanceControllerGetMySummary>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAttendanceControllerGetMySummary<TData = Awaited<ReturnType<typeof attendanceControllerGetMySummary>>, TError = unknown>(
 params: AttendanceControllerGetMySummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerGetMySummary>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof attendanceControllerGetMySummary>>,
          TError,
          Awaited<ReturnType<typeof attendanceControllerGetMySummary>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAttendanceControllerGetMySummary<TData = Awaited<ReturnType<typeof attendanceControllerGetMySummary>>, TError = unknown>(
 params: AttendanceControllerGetMySummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerGetMySummary>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 自身の月次集計
 */

export function useAttendanceControllerGetMySummary<TData = Awaited<ReturnType<typeof attendanceControllerGetMySummary>>, TError = unknown>(
 params: AttendanceControllerGetMySummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerGetMySummary>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAttendanceControllerGetMySummaryQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary テナント内全従業員の勤怠一覧（tenant_admin）
 */
export const attendanceControllerFindAllAdmin = (
    params?: AttendanceControllerFindAllAdminParams,
 signal?: AbortSignal
) => {


      return httpRequest<AttendanceListResponseDto>(
      {url: `/api/v1/admin/attendance`, method: 'GET',
        params, signal
    },
      );
    }




export const getAttendanceControllerFindAllAdminQueryKey = (params?: AttendanceControllerFindAllAdminParams,) => {
    return [
    `/api/v1/admin/attendance`, ...(params ? [params] : [])
    ] as const;
    }


export const getAttendanceControllerFindAllAdminQueryOptions = <TData = Awaited<ReturnType<typeof attendanceControllerFindAllAdmin>>, TError = unknown>(params?: AttendanceControllerFindAllAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerFindAllAdmin>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAttendanceControllerFindAllAdminQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof attendanceControllerFindAllAdmin>>> = ({ signal }) => attendanceControllerFindAllAdmin(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerFindAllAdmin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AttendanceControllerFindAllAdminQueryResult = NonNullable<Awaited<ReturnType<typeof attendanceControllerFindAllAdmin>>>
export type AttendanceControllerFindAllAdminQueryError = unknown


export function useAttendanceControllerFindAllAdmin<TData = Awaited<ReturnType<typeof attendanceControllerFindAllAdmin>>, TError = unknown>(
 params: undefined |  AttendanceControllerFindAllAdminParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerFindAllAdmin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof attendanceControllerFindAllAdmin>>,
          TError,
          Awaited<ReturnType<typeof attendanceControllerFindAllAdmin>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAttendanceControllerFindAllAdmin<TData = Awaited<ReturnType<typeof attendanceControllerFindAllAdmin>>, TError = unknown>(
 params?: AttendanceControllerFindAllAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerFindAllAdmin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof attendanceControllerFindAllAdmin>>,
          TError,
          Awaited<ReturnType<typeof attendanceControllerFindAllAdmin>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAttendanceControllerFindAllAdmin<TData = Awaited<ReturnType<typeof attendanceControllerFindAllAdmin>>, TError = unknown>(
 params?: AttendanceControllerFindAllAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerFindAllAdmin>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary テナント内全従業員の勤怠一覧（tenant_admin）
 */

export function useAttendanceControllerFindAllAdmin<TData = Awaited<ReturnType<typeof attendanceControllerFindAllAdmin>>, TError = unknown>(
 params?: AttendanceControllerFindAllAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerFindAllAdmin>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAttendanceControllerFindAllAdminQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary テナント内月次集計（tenant_admin）
 */
export const attendanceControllerGetAdminSummary = (
    params: AttendanceControllerGetAdminSummaryParams,
 signal?: AbortSignal
) => {


      return httpRequest<AttendanceSummaryResponseDto>(
      {url: `/api/v1/admin/attendance/summary`, method: 'GET',
        params, signal
    },
      );
    }




export const getAttendanceControllerGetAdminSummaryQueryKey = (params?: AttendanceControllerGetAdminSummaryParams,) => {
    return [
    `/api/v1/admin/attendance/summary`, ...(params ? [params] : [])
    ] as const;
    }


export const getAttendanceControllerGetAdminSummaryQueryOptions = <TData = Awaited<ReturnType<typeof attendanceControllerGetAdminSummary>>, TError = unknown>(params: AttendanceControllerGetAdminSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerGetAdminSummary>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAttendanceControllerGetAdminSummaryQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof attendanceControllerGetAdminSummary>>> = ({ signal }) => attendanceControllerGetAdminSummary(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerGetAdminSummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AttendanceControllerGetAdminSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof attendanceControllerGetAdminSummary>>>
export type AttendanceControllerGetAdminSummaryQueryError = unknown


export function useAttendanceControllerGetAdminSummary<TData = Awaited<ReturnType<typeof attendanceControllerGetAdminSummary>>, TError = unknown>(
 params: AttendanceControllerGetAdminSummaryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerGetAdminSummary>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof attendanceControllerGetAdminSummary>>,
          TError,
          Awaited<ReturnType<typeof attendanceControllerGetAdminSummary>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAttendanceControllerGetAdminSummary<TData = Awaited<ReturnType<typeof attendanceControllerGetAdminSummary>>, TError = unknown>(
 params: AttendanceControllerGetAdminSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerGetAdminSummary>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof attendanceControllerGetAdminSummary>>,
          TError,
          Awaited<ReturnType<typeof attendanceControllerGetAdminSummary>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAttendanceControllerGetAdminSummary<TData = Awaited<ReturnType<typeof attendanceControllerGetAdminSummary>>, TError = unknown>(
 params: AttendanceControllerGetAdminSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerGetAdminSummary>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary テナント内月次集計（tenant_admin）
 */

export function useAttendanceControllerGetAdminSummary<TData = Awaited<ReturnType<typeof attendanceControllerGetAdminSummary>>, TError = unknown>(
 params: AttendanceControllerGetAdminSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof attendanceControllerGetAdminSummary>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAttendanceControllerGetAdminSummaryQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




