/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * 勤怠管理システム API
 * マルチテナント勤怠管理システムのREST API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ClosingControllerFindAllParams,
  CreateClosingDto
} from '../../model';

import { customAxios } from '../../http-client';




/**
 * @summary 締め実行
 */
export const closingControllerClose = (
    createClosingDto: CreateClosingDto,
 signal?: AbortSignal
) => {


      return customAxios<void>(
      {url: `/api/v1/admin/closing`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createClosingDto, signal
    },
      );
    }



export const getClosingControllerCloseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof closingControllerClose>>, TError,{data: CreateClosingDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof closingControllerClose>>, TError,{data: CreateClosingDto}, TContext> => {

const mutationKey = ['closingControllerClose'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof closingControllerClose>>, {data: CreateClosingDto}> = (props) => {
          const {data} = props ?? {};

          return  closingControllerClose(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClosingControllerCloseMutationResult = NonNullable<Awaited<ReturnType<typeof closingControllerClose>>>
    export type ClosingControllerCloseMutationBody = CreateClosingDto
    export type ClosingControllerCloseMutationError = unknown

    /**
 * @summary 締め実行
 */
export const useClosingControllerClose = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof closingControllerClose>>, TError,{data: CreateClosingDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof closingControllerClose>>,
        TError,
        {data: CreateClosingDto},
        TContext
      > => {
      return useMutation(getClosingControllerCloseMutationOptions(options), queryClient);
    }
    /**
 * @summary 締め履歴一覧
 */
export const closingControllerFindAll = (
    params: ClosingControllerFindAllParams,
 signal?: AbortSignal
) => {


      return customAxios<void>(
      {url: `/api/v1/admin/closing`, method: 'GET',
        params, signal
    },
      );
    }




export const getClosingControllerFindAllQueryKey = (params?: ClosingControllerFindAllParams,) => {
    return [
    `/api/v1/admin/closing`, ...(params ? [params] : [])
    ] as const;
    }


export const getClosingControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof closingControllerFindAll>>, TError = unknown>(params: ClosingControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof closingControllerFindAll>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getClosingControllerFindAllQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof closingControllerFindAll>>> = ({ signal }) => closingControllerFindAll(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof closingControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ClosingControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof closingControllerFindAll>>>
export type ClosingControllerFindAllQueryError = unknown


export function useClosingControllerFindAll<TData = Awaited<ReturnType<typeof closingControllerFindAll>>, TError = unknown>(
 params: ClosingControllerFindAllParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof closingControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof closingControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof closingControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useClosingControllerFindAll<TData = Awaited<ReturnType<typeof closingControllerFindAll>>, TError = unknown>(
 params: ClosingControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof closingControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof closingControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof closingControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useClosingControllerFindAll<TData = Awaited<ReturnType<typeof closingControllerFindAll>>, TError = unknown>(
 params: ClosingControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof closingControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 締め履歴一覧
 */

export function useClosingControllerFindAll<TData = Awaited<ReturnType<typeof closingControllerFindAll>>, TError = unknown>(
 params: ClosingControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof closingControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getClosingControllerFindAllQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary 締め再開
 */
export const closingControllerReopen = (
    id: string,
 signal?: AbortSignal
) => {


      return customAxios<void>(
      {url: `/api/v1/admin/closing/${id}/reopen`, method: 'POST', signal
    },
      );
    }



export const getClosingControllerReopenMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof closingControllerReopen>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof closingControllerReopen>>, TError,{id: string}, TContext> => {

const mutationKey = ['closingControllerReopen'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof closingControllerReopen>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  closingControllerReopen(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClosingControllerReopenMutationResult = NonNullable<Awaited<ReturnType<typeof closingControllerReopen>>>

    export type ClosingControllerReopenMutationError = unknown

    /**
 * @summary 締め再開
 */
export const useClosingControllerReopen = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof closingControllerReopen>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof closingControllerReopen>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getClosingControllerReopenMutationOptions(options), queryClient);
    }
